export const DEMO_BLOG = {
  site: {
    title: 'Generator Demo',
    description: "A showcase of this generator's design and features",
    url: 'https://jsonblog.org',
  },
  basics: {
    name: 'JSONBlog Team',
    email: 'hello@jsonblog.org',
  },
  posts: [
    {
      title: 'Welcome to JSONBlog',
      content: `# Welcome to JSONBlog

This is a demo post showing how your content will look with this generator.

## Markdown Support

Full markdown support with **bold**, *italic*, and \`inline code\`.

## Code Blocks

\`\`\`javascript
const blog = {
  site: { title: 'My Blog' },
  posts: [
    { title: 'Hello World', content: '# Hello!' }
  ]
};
\`\`\`

## Lists and More

- Clean typography
- Responsive design
- Fast loading

> Blockquotes look great too!`,
      createdAt: '2025-01-20',
      tags: ['demo', 'welcome'],
      categories: ['General'],
    },
    {
      title: 'Syntax Highlighting Demo',
      content: `# Syntax Highlighting

This generator includes beautiful syntax highlighting for code blocks.

\`\`\`typescript
interface BlogPost {
  title: string;
  content: string;
  createdAt: string;
  tags?: string[];
}
\`\`\`

\`\`\`python
def generate_blog(data, output_dir):
    for post in data['posts']:
        render_post(post, output_dir)
\`\`\``,
      createdAt: '2025-01-19',
      tags: ['demo', 'code'],
      categories: ['Technical'],
    },
    {
      title: 'AI-Generated Content Example',
      content: `# AI Content Indicator

This post demonstrates how AI-generated content is displayed.

Posts marked as AI-generated get special styling to distinguish them from human-written content.`,
      createdAt: '2025-01-18',
      type: 'ai',
      tags: ['demo', 'ai'],
      categories: ['AI'],
    },
  ],
  pages: [
    {
      title: 'About',
      content: `# About This Demo

This is a demo site generated by JSONBlog to showcase the generator's design and features.

Visit [jsonblog.org](https://jsonblog.org) to learn more.`,
    },
  ],
};
