#!/usr/bin/env node
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';
import { generateBlog as generateBoilerplate } from '@jsonblog/generator-boilerplate';
import { generateBlog as generateTailwind } from '@jsonblog/generator-tailwind';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PUBLIC_DIR = join(__dirname, '..', 'public');
const DEMOS_DIR = join(PUBLIC_DIR, 'demos');

// Demo blog data
const demoBlog = {
  site: {
    title: 'Generator Demo',
    description: 'A demo blog showing off JSONBlog generator features',
    url: 'https://jsonblog.dev/demos'
  },
  basics: {
    name: 'Demo Author',
    email: 'demo@jsonblog.dev',
    url: 'https://jsonblog.dev'
  },
  posts: [
    {
      title: 'Welcome to JSONBlog',
      slug: 'welcome',
      content: `This is a demo post showing how your content will look with this generator.

## Markdown Support

Full markdown support with **bold**, _italic_, and \`inline code\`.

## Code Blocks

\`\`\`javascript
const blog = {
  site: { title: 'My Blog' },
  posts: [
    { title: 'Hello World', content: '# Hello!' }
  ]
};
\`\`\`

## Lists

- Clean typography
- Responsive design
- Fast loading
`,
      createdAt: '2025-01-20',
      tags: ['demo', 'welcome']
    },
    {
      title: 'Syntax Highlighting Demo',
      slug: 'syntax',
      content: `\`\`\`typescript
interface BlogPost {
  title: string;
  content: string;
  createdAt: string;
}
\`\`\``,
      createdAt: '2025-01-19',
      tags: ['demo', 'code']
    },
    {
      title: 'AI Content Example',
      slug: 'ai',
      content: 'This demonstrates AI-generated content styling with dimmed appearance.',
      createdAt: '2025-01-18',
      type: 'ai'
    }
  ],
  pages: [
    {
      title: 'About',
      slug: 'about',
      content: '# About\n\nThis is a demo blog generated by JSONBlog.'
    }
  ]
};

async function buildDemo(generatorName, generatorFn, outputSubdir) {
  console.log(`\nBuilding demo for ${generatorName}...`);

  const outputDir = join(DEMOS_DIR, outputSubdir);

  // Clean and create output directory
  if (fs.existsSync(outputDir)) {
    fs.rmSync(outputDir, { recursive: true, force: true });
  }
  fs.mkdirSync(outputDir, { recursive: true });

  // Create a demo blog with URL prefixed to the demo subdirectory
  const demoBlogWithPrefix = {
    ...demoBlog,
    site: {
      ...demoBlog.site,
      url: `https://jsonblog.dev/demos/${outputSubdir}`
    },
    meta: {
      canonical: `https://jsonblog.dev/demos/${outputSubdir}`
    }
  };

  // Generate files using the generator with URL prefix config
  const generatorConfig = {
    urlPrefix: `/demos/${outputSubdir}`
  };

  const files = await generatorFn(demoBlogWithPrefix, __dirname, generatorConfig);

  console.log(`Generated ${files.length} files for ${generatorName}`);

  // Write each file to disk, fixing absolute paths in HTML files
  files.forEach((file) => {
    const filePath = join(outputDir, file.name);
    const fileDir = dirname(filePath);

    // Ensure directory exists
    if (!fs.existsSync(fileDir)) {
      fs.mkdirSync(fileDir, { recursive: true });
    }

    let content = file.content;

    // Fix absolute paths in HTML files to work with static hosting
    if (file.name.endsWith('.html')) {
      // Replace absolute paths with relative paths (relative to base URL)
      content = content
        .replace(/href="\/main\.css"/g, `href="main.css"`)
        .replace(/href="\/rss\.xml"/g, `href="rss.xml"`)
        .replace(/href="\/([^"]+)"/g, (match, path) => {
          // Skip external URLs, already relative paths, and base tags
          if (path.startsWith('http') || path.startsWith('.') || path.startsWith('#') || path.startsWith('demos/')) {
            return match;
          }
          return `href="${path}"`;
        });

      // Add base tag AFTER path replacements to avoid it being modified
      // With base tag, all relative paths resolve from the base URL
      const baseUrl = `/demos/${outputSubdir}/`;
      const baseTag = `  <base href="${baseUrl}">\n`;

      // Insert base tag right after <head>
      content = content.replace(/(<head>)\s*\n/, `$1\n${baseTag}`);
    }

    console.log(`  Writing: ${file.name}`);
    fs.writeFileSync(filePath, content, 'utf8');
  });

  console.log(`✓ ${generatorName} demo built successfully at ${outputDir}`);
}

async function main() {
  console.log('Building generator demos...\n');

  // Ensure demos directory exists
  fs.mkdirSync(DEMOS_DIR, { recursive: true });

  // Build each generator demo
  await buildDemo('generator-boilerplate', generateBoilerplate, 'boilerplate');
  await buildDemo('generator-tailwind', generateTailwind, 'tailwind');

  console.log('\n✓ All demos built successfully!');
}

main().catch((error) => {
  console.error('Error building demos:', error);
  process.exit(1);
});
